#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx',
    source=bld.path.ant_glob('**/*.cpp'),
    target='kodo',
    cxxflags=['-Wno-warn-absolute-paths'],
    linkflags=['--bind'],
    use=['kodo_rlnc_includes'],
    export_includes=['..'])


